### ISSUE TITLE
Download failed

### ISSUE THREAD

**Issue by samrit2442** [albtree/cricreadR#1]
It could not be downloaded. Showing the following error.
`Using GitHub PAT from the git credential store.
Downloading GitHub repo albtree/cricreadR@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/albtree/cricreadR/tarball/HEAD' failed`

**Comment by albtree** [comment]
Thanks for logging. I suspect it’s because I’ve got too many large files in the package so the download can timeout. Will look into it

**Comment by albtree** [comment]
I was able to re-create the issue and think it has been fixed.
try remove the package and re-install
```
remove.packages("cricreadR")
devtools::install_github("albtree/cricreadR")

**Comment by samrit2442** [comment]
But I am still getting the same error.

**Comment by albtree** [comment]
I have reduced the download size smaller again which should reduce the chance of it timing out. Are you able to try again?

```
remove.packages("cricreadR")
devtools::install_github("albtree/cricreadR")
```

**Comment by samrit2442** [comment]
https://github.com/albtree/cricreadR/assets/48163065/6a8af8b3-deab-43b7-b086-b8cfba1a4cd4

Still not able to install the package. Attached is the recording (please ignore background noise)

**Comment by albtree** [comment]
Can you run packageVersion(“cricreadR”) and post the output please?

**Comment by samrit2442** [comment]
`packageVersion(“cricreadR”)` this command is not executing as the package itself did not got installed.
![image](https://github.com/albtree/cricreadR/assets/48163065/d6ab76d2-b997-4943-b7b7-c1cce4d32c36)
